source 'https://rubygems.org'

gem 'cookstyle'
gem 'chefspec'
gem 'veil', git: 'https://github.com/chef/chef_secrets.git'

# pin to Ruby 2.6 compatible versions until we bump to Ruby 2.7+

# chef-cli pulls chef >= 15.0 which is 16.1.16 at the time of failure.
gem 'chef', '~> 15.17'

# chef-cli >=3.0.4 requires Ruby version >= 2.7 which chef-server isn't ready for
gem 'chef-cli', '=3.0.1'
